# Generated by Django 5.0.4 on 2024-04-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SistemaInventario_api",
            "0002_rename_codigo_barra_producto_fecha_de_caducidad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="fecha_de_caducidad",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
