# Generated by Django 5.0.4 on 2024-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SistemaInventario_api", "0004_alter_producto_fecha_de_caducidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="fecha_de_caducidad",
            field=models.DateField(blank=True, null=True),
        ),
    ]
