# Generated by Django 5.0.4 on 2024-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SistemaInventario_api", "0005_alter_producto_fecha_de_caducidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="movimientodeinventario",
            name="departamento_salida",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
