# Generated by Django 5.0.4 on 2024-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SistemaInventario_api",
            "0007_alter_movimientodeinventario_departamento_salida",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
