# Generated by Django 5.0.4 on 2024-04-28 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SistemaInventario_api",
            "0008_alter_departamento_nombre_alter_producto_nombre",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InventarioDepartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_en_stock", models.IntegerField(default=0)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SistemaInventario_api.departamento",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SistemaInventario_api.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario por Departamento",
                "verbose_name_plural": "Inventarios por Departamento",
                "unique_together": {("departamento", "producto")},
            },
        ),
    ]
