# Generated by Django 5.0.4 on 2024-04-28 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SistemaInventario_api", "0009_inventariodepartamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movimientodeinventario",
            old_name="departamento_salida",
            new_name="departamento",
        ),
    ]
