# Generated by Django 5.0.4 on 2024-06-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SistemaInventario_api",
            "0010_rename_departamento_salida_movimientodeinventario_departamento",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
        migrations.AddField(
            model_name="producto",
            name="procedencia",
            field=models.CharField(default="null", max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                check=models.Q(("cantidad_en_stock__gte", 0)),
                name="cantidad_en_stock_gte_0",
            ),
        ),
    ]
